spring:
  profiles:
    active: dev
  servlet:
    multipart:
      #最大文件大小。值可以使用后缀“MB”或“KB”。指示兆字节或千字节大小。
      max-file-size: 100MB
      # 最大请求大小可以是mb也可以是kb
      max-request-size: 100MB
  banner:
    charset: UTF-8
    location: classpath:static/banner.txt
    resources:
      add-mappings: true
server:
  port: 9082
