

swagger:
  base-package: com
  title: 文件 Api
  enabled: true
  authorization:
    key-name: authorization

config:
#  file-host: 103.119.45.125
  file-host: 47.92.213.93
  file-port: 9082
  file-path: /root/project/img
  file-url: upload
  file-type: java,php,py,go